(add-to-list 'load-path "~/.emacs.d/")

(load "config/emacs/env")
(load "config/emacs/global")
(load "config/emacs/bindings")
(load "config/emacs/defuns")
(load "config/emacs/utf-8")
(load "config/emacs/frames")
(load "config/emacs/theme")
(load "config/emacs/tabs")
(load "config/emacs/scratch")
(load "config/emacs/save-place")
(load "config/emacs/disabled")
(load "config/emacs/tramp")

(load "config/pkgs/package")
(load "config/pkgs/ido")
(load "config/pkgs/flyspell")
(load "config/pkgs/uniquify")
(load "config/pkgs/eshell")

(load "config/pkgs/auto-complete")
(load "config/pkgs/enh-ruby")
(load "config/pkgs/js2")
(load "config/pkgs/perl")
