(add-to-list 'load-path "~/.emacs.d/config")

(load "emacs/env")
(load "emacs/global")
(load "emacs/bindings")
(load "emacs/defuns")
(load "emacs/utf-8")
(load "emacs/frames")
(load "emacs/theme")
(load "emacs/tabs")
(load "emacs/scratch")
(load "emacs/save-place")
(load "emacs/disabled")
(load "emacs/tramp")
(load "emacs/bookmark")

(load "pkgs/package")
(load "pkgs/ido")
(load "pkgs/flyspell")
(load "pkgs/uniquify")
(load "pkgs/eshell")

(load "pkgs/auto-complete")
(load "pkgs/enh-ruby")
(load "pkgs/js2")
(load "pkgs/perl")
(load "pkgs/org")
(load "pkgs/magit")
(load "pkgs/gnus")
(load "pkgs/markdown")
