;;; envmon-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from envmon.el

(push '(envmon 0 2 0) package--builtin-versions)
(autoload 'envmon-with-environment-alist "envmon" "\
Run BODY with environment from ENVIRONMENT-ALIST.

NB. soft reimplementation of `with-environment-variables'.

(fn ENVIRONMENT-ALIST &rest BODY)" nil t)
(autoload 'envmon-rollback-generation "envmon" "\
Rollback state to youngest generation in history." t)
(autoload 'envmon-shell-executable "envmon" "\
Locate shell program from which to fetch environment varialbes.")
(autoload 'envmon-shell-executable-arguments "envmon" "\
Allow user override of default arguemnts map.")
(defvar envmon-mode nil "\
Non-nil if Envmon mode is enabled.
See the `envmon-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `envmon-mode'.")
(custom-autoload 'envmon-mode "envmon" nil)
(autoload 'envmon-mode "envmon" "\
Ingest environment variables from POSIX shell.

This is a global minor mode.  If called interactively, toggle the
`Envmon mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='envmon-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'envmon-mode-enable "envmon" "\
Unconditionally enable `envmon-mode'.")
(autoload 'envmon-mode-disable "envmon" "\
Unconditionally disable `envmon-mode'.")
(register-definition-prefixes "envmon" '("envmon-"))


;;; Generated autoloads from envmon-table.el

(push '(envmon-table 0 2 0) package--builtin-versions)
(register-definition-prefixes "envmon-table" '("envmon-"))


;;; Generated autoloads from envmon-test.el

(push '(envmon-test 0 2 0) package--builtin-versions)

;;; End of scraped data

(provide 'envmon-autoloads)

;; Local Variables:
;; version-control: never
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; envmon-autoloads.el ends here
